Update block-updates.md
hacks-guide/Guide-WiiU pull request #107
Opened 2021-07-13 03:34 UTC by quadsYT

2021-07-13 08:35 UTC, GaryOderNichts requested changes
Also the sentence is technically still valid without your changes. It's not required to list every single update to make the point that blocking updates is recommended.

2021-07-13 08:35 UTC, GaryOderNichts commented on docs/extras/block-updates.md
> +All currently known Wii U exploits can, unlike e.g. the Nintendo Switch RCM exploit, be patched by a system update. Although the Wii U is no longer officially supported, Nintendo may still release up
Don't use "both" when referring to 3 updates.

2021-07-14 00:09 UTC, quadsYT commented on docs/extras/block-updates.md
> +All currently known Wii U exploits can, unlike e.g. the Nintendo Switch RCM exploit, be patched by a system update. Although the Wii U is no longer officially supported, Nintendo may still release up
Ah okay

2021-07-18 01:28 UTC, quadsYT commented
@GaryOderNichts  Done.

2021-08-24 16:18 UTC, merged