Clarify B button requirement on Browser Exploit step
hacks-guide/Guide-WiiU pull request #140
Opened 2022-08-29 19:41 UTC by nikitalita

It's easy to miss the "holding the B button" requirement as it is part of a compound sentence, so I made it bold and added clarifying bullet points telling the user what they should see if they successfully completed the step.

2022-08-30 13:42 UTC, GaryOderNichts requested changes

2022-08-30 13:42 UTC, GaryOderNichts commented on docs/user-guide/tiramisu/browser-exploit.md
> +    - If you held the B button after clicking `Run Exploit!`, you should see a menu listing `default` and `nanddumper` as options. This is the menu required for the next step.
Can you change this to something like `a menu prompting you to choose a payload.` or 
```
you should see a `Please choose your payload:` message.
```
?

2022-08-30 13:42 UTC, GaryOderNichts commented on docs/user-guide/tiramisu/browser-exploit.md
> +    - If you did not hold the B button after clicking `Run Exploit!`, you will see a menu listing `installer` and `tiramisu` as options. If you see this menu, reboot the console and try again.
```suggestion
    - If you did not hold the B button after clicking `Run Exploit!`, you will see the `Environment Loader`. If you see this menu, reboot the console and try again.
```

2023-10-21 22:59 UTC, Lazr1026 commented
Closing as none of the suggested changes were done and #191 does exactly what this does

2023-10-21 22:59 UTC, closed without merging