nand-backup.md grammar adjustment
hacks-guide/Guide-WiiU pull request #171
Opened 2023-03-14 21:47 UTC by BttrDrgn

1. When the process completed,... to
1. When the process *is* completed,...

2023-03-14 21:55 UTC, MechanicalDragon0687 commented
not to be that person, but wouldnt it be "when the process has completed".  a process (noun) can have completed some action, which is what is implied here: when the process completed [whatever it was doing]. a process is complete.

2023-03-14 22:10 UTC, lilyuwuu commented
i would probably change it to "Once the process is complete" but I would agree on "process has completed" or "process has been completed" as well

2023-10-22 03:29 UTC, Lazr1026 requested changes

2023-10-22 03:29 UTC, Lazr1026 commented on docs/user-guide/tiramisu/nand-backup.md
> +1. When the process is completed, power off your Wii U, take your SD Card out of the Wii U and plug it into your PC.
I'd be more than happy to merge if this is changed to:
```suggestion
1. When the process has completed, power off your Wii U, take your SD Card out of the Wii U and plug it into your PC.
```

2024-03-28 01:58 UTC, closed without merging